### ISSUE TITLE
听有些音频的时候会卡

### ISSUE THREAD

**Issue by fcx891231** [yuedu-fm/yuedu-ios#1]
播放音频的时候会有卡顿的感觉,声音断断续续的莫非是我网速太卡了.
在tableView上下滚动的时候底部那个条跳来跳去的,
你的源码我看了写的相当给力啊.三个月搞定么大神.

**Comment by smallmuou** [comment]
（1）播放音乐卡，瓶颈是悦读FM服务器带宽较小，目前5MB/s.
（2）由于是采用分批加载，因此会有些跳变，慢速滑动，效果还可以；
（3）主要是业余时间开发，因此时间周期会长点

**Comment by fcx891231** [comment]
有个小bug,详情页中间那个播放图标状态没和底部的同步.如果播放的时候点击详情页中间那个会出现两个声音.
手机在点击某些cell的时候会出现黑屏然后app卡死,也许是我手机问题.哈哈```

**Comment by smallmuou** [comment]
(1) 详情页是悦读FM网站的网页，带有播放按钮，暂时没有去除，后期会考虑移除.
(2) 点击cell卡死，是必现的吗？
